export const SET_LOADING = "SET_LOADING";
export const CLEAR_LOADING = "CLEAR_LOADING";

export const SET_ERROR = "SET_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";

export const GET_ALL_TYPES = "GET_ALL_TYPES";

export const GET_ALL_ATTRIBUTES = "GET_ALL_ATTRIBUTES";

export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";

export const SIGNUP = "SIGNUP";
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

export const GET_ALL_CARDS = "GET_ALL_CARDS";
export const GET_CARD_BY_ID = "GET_CARD_BY_ID";
export const ADD_CARD = "ADD_CARD";
export const EDIT_CARD = "EDIT_CARD";
export const DELETE_CARD = "DELETE_CARD";
export const ASSIGN_MONSTER_TO_CATEGORY = "ASSIGN_MONSTER_TO_CATEGORY";

export const GET_ALL_SPELL_CARDS = "GET_ALL_SPELL_CARDS";
export const GET_SPELL_CARD_BY_ID = "GET_SPELL_CARD_BY_ID";
export const ADD_SPELL_CARD = "ADD_SPELL_CARD";
export const EDIT_SPELL_CARD = "EDIT_SPELL_CARD";
export const DELETE_SPELL_CARD = "DELETE_SPELL_CARD";

export const GET_ALL_TRAP_CARDS = "GET_ALL_TRAP_CARDS";
export const GET_TRAP_CARD_BY_ID = "GET_TRAP_CARD_BY_ID";
export const ADD_TRAP_CARD = "ADD_TRAP_CARD";
export const EDIT_TRAP_CARD = "EDIT_TRAP_CARD";
export const DELETE_TRAP_CARD = "DELETE_TRAP_CARD";

export const GET_ALL_DECKS = "GET_ALL_DECKS";
export const GET_DECKS_BY_USER_ID = "GET_DECKS_BY_USER_ID";
export const GET_DECK_BY_ID = "GET_DECK_BY_ID";
export const ADD_DECK = "ADD_DECK";
export const ASSIGN_MONSTER_CARD_TO_DECK = "ASSIGN_MONSTER_CARD_TO_DECK";
export const ASSIGN_SPELL_CARD_TO_DECK = "ASSIGN_SPELL_CARD_TO_DECK";
export const ASSIGN_TRAP_CARD_TO_DECK = "ASSIGN_TRAP_CARD_TO_DECK";
export const REMOVE_MONSTER_CARD_OF_DECK = "REMOVE_MONSTER_CARD_OF_DECK";
export const REMOVE_SPELL_CARD_OF_DECK = "REMOVE_SPELL_CARD_OF_DECK";
export const REMOVE_TRAP_CARD_OF_DECK = "REMOVE_TRAP_CARD_OF_DECK";
export const EDIT_DECK = "EDIT_DECK";
export const DELETE_DECK = "DELETE_DECK";
